name:                krill
version:             0.1.0.0
github:              "coffee-cup/krill"
license:             BSD3
author:              "Jake Runzer"
maintainer:          "jakerunzer@gmail.com"
copyright:           "2019 Jake Runzer"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/krill#readme>

dependencies:
- base                 >= 4.7   && < 5
- containers           >= 0.6   && < 0.7
- haskeline            >= 0.7   && < 0.8
- mtl                  >= 2.2   && < 2.3
- optparse-applicative >= 0.14  && < 0.15
- pretty               >= 1.1   && < 1.2
- repline              >= 0.2.0 && < 0.3
- text                 >= 1.2   && < 1.3
- transformers         >= 0.5.2 && < 0.6
- megaparsec           >= 7.0.4 && < 7.1

default-extensions:
  - OverloadedStrings

library:
  source-dirs: src

executables:
  krill:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - krill

tests:
  krill-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - krill
